// Builds the self-contained "hello" MCP App widget.
//
// esbuild bundles src/view.js together with the vendored MCP Apps SDK
// (vendor/mcp-app-sdk.js) into one inline <script>, which we splice into
// src/shell.html. The result is a single HTML document with no external
// dependencies — exactly what a sandboxed, null-origin MCP App iframe needs.
//
// Output: app/mcp/widget.ts (a generated string constant the /mcp route serves).
// This keeps @modelcontextprotocol/ext-apps out of the site's runtime deps —
// its install step rebuilds from source and fails on Vercel — while still using
// the real, protocol-correct client.
//
// Run: npm install && npm run build   (from this directory)

import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");

// 1. Bundle the view + SDK into a single self-executing script (no imports left).
const result = await build({
  entryPoints: [join(here, "src", "view.js")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  legalComments: "none",
  write: false,
});
const script = result.outputFiles[0].text;

// 2. Splice it into the HTML shell.
const shell = await readFile(join(here, "src", "shell.html"), "utf8");
// Use a function replacement: the minified bundle contains `$\`` / `$&`
// sequences (from `${...}` template literals) that a string replacement would
// interpret as special patterns and corrupt. A function is inserted verbatim.
const html = shell.replace(
  "<!--APP-SCRIPT-->",
  () => `<script>\n${script}</script>`,
);

// 3. Emit the generated TypeScript module the route imports.
const banner =
  "// GENERATED by research/mcp-app/build.mjs — do not edit by hand.\n" +
  "// Single-file 'hello' MCP App: HTML shell + the bundled MCP Apps SDK client.\n" +
  "// Regenerate with: cd research/mcp-app && npm install && npm run build\n\n";
const out = `${banner}export const HELLO_WIDGET_HTML = ${JSON.stringify(html)};\n`;

const target = join(repoRoot, "app", "mcp", "widget.ts");
await writeFile(target, out);
console.log(`Wrote ${target} (${out.length} bytes, html ${html.length} bytes)`);
