/**
 * Synthetic verification harness for v1 pose estimators.
 *
 * Feeds each algorithm a set of pixel-x + map-point observations generated by
 * projecting known map points through a KNOWN ground-truth camera, then
 * measures how closely each estimator recovers that camera.
 *
 * This bypasses the UI entirely, so it exercises ONLY the algorithm math —
 * any coordinate-system issues elsewhere in the app don't interfere.
 */

import {
  estimateCentroid,
  estimateJointGN,
  estimateJointGNRansac,
  estimateRatioGN,
  wrapAngle,
} from './algorithms'

// ─── Seeded PRNG (LCG) so scenarios are reproducible ──────────────────────────
function lcg(seed) {
  let s = (seed >>> 0) || 1
  return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 2 ** 32 }
}

// ─── Pinhole projection ───────────────────────────────────────────────────────
// Horizontal-only: the camera is on the y=0 plane looking along heading angle h.
// u = cx_px + f · tan(θ - h), where θ is the world-azimuth from camera to anchor.
function focalFromFov(fovDeg, photoWidth) {
  return photoWidth / (2 * Math.tan((fovDeg * Math.PI / 180) / 2))
}

export function projectMapPoint(cam, mapPoint, photoWidth) {
  const cx_px = photoWidth / 2
  const f     = focalFromFov(cam.fov, photoWidth)
  const theta = Math.atan2(mapPoint.x - cam.px, -(mapPoint.z - cam.pz))
  const beta  = theta - cam.heading
  // Points behind the camera or beyond ±90° from optical axis have undefined
  // projection (tan blows up). Mark those with NaN so the caller can drop them.
  if (Math.abs(beta) >= Math.PI / 2 - 1e-6) return NaN
  return cx_px + f * Math.tan(beta)
}

// ─── Scenario generation ──────────────────────────────────────────────────────
function generateMapPoints(rng, n, cam, extent) {
  const halfFovRad = (cam.fov * Math.PI / 180) / 2 * 0.9   // stay away from edges
  const pts = []
  let guard = 0
  while (pts.length < n && guard++ < 2000) {
    const angle = cam.heading + (rng() - 0.5) * 2 * halfFovRad
    const dist  = extent.near + rng() * (extent.far - extent.near)
    pts.push({
      x: cam.px + Math.sin(angle) * dist,
      z: cam.pz - Math.cos(angle) * dist,
    })
  }
  return pts
}

function makeObservations(cam, mapPoints, photoWidth, noisePx, rng) {
  const out = []
  for (const mp of mapPoints) {
    const uTrue = projectMapPoint(cam, mp, photoWidth)
    if (!Number.isFinite(uTrue)) continue
    if (uTrue < -photoWidth || uTrue > photoWidth * 2) continue   // wildly off-screen
    const noise = noisePx > 0 ? (rng() - 0.5) * 2 * noisePx : 0
    out.push({ photoX: uTrue + noise, mapPoint: mp })
  }
  return out
}

// ─── Run one trial of one scenario ────────────────────────────────────────────
const ALGOS = [
  { id: 'centroid',  fn: estimateCentroid },
  { id: 'jointGN',   fn: estimateJointGN },
  { id: 'ratioGN',   fn: estimateRatioGN },
  { id: 'jointRSC',  fn: estimateJointGNRansac },
]

export function runTrial(scenario, rng) {
  const mapPts = generateMapPoints(rng, scenario.n, scenario.cam, scenario.extent)
  const obs    = makeObservations(scenario.cam, mapPts, scenario.photoWidth, scenario.noisePx, rng)
  if (obs.length < 4) return null

  const ctx = { photoWidth: scenario.photoWidth }
  const truth = scenario.cam
  const results = {}

  for (const { id, fn } of ALGOS) {
    const t0 = performance.now()
    let r = null
    try { r = fn(obs, ctx) } catch { r = null }
    const dt = performance.now() - t0
    if (!r) { results[id] = { ok: false, dt }; continue }

    const posErr     = Math.hypot(r.px - truth.px, r.pz - truth.pz)
    const headingErr = Number.isFinite(r.heading)
      ? Math.abs(wrapAngle(r.heading - truth.heading)) * 180 / Math.PI
      : NaN
    const fovErr = Number.isFinite(r.fov) ? Math.abs(r.fov - truth.fov) : NaN
    results[id] = { ok: true, posErr, headingErr, fovErr, dt }
  }
  return { used: obs.length, results }
}

// ─── Aggregate ────────────────────────────────────────────────────────────────
function stats(arr) {
  const a = arr.filter(Number.isFinite).sort((x, y) => x - y)
  if (a.length === 0) return { n: 0 }
  const pick = (p) => a[Math.min(a.length - 1, Math.floor(a.length * p))]
  return {
    n: a.length,
    median: pick(0.5),
    p95:    pick(0.95),
    mean:   a.reduce((s, v) => s + v, 0) / a.length,
    max:    a[a.length - 1],
  }
}

function summarize(trials) {
  const per = {}
  for (const { id } of ALGOS) {
    const rs = trials.map(t => t.results[id]).filter(r => r && r.ok)
    if (!rs.length) { per[id] = { trials: 0 }; continue }
    per[id] = {
      trials:   rs.length,
      pos:      stats(rs.map(r => r.posErr)),
      heading:  stats(rs.map(r => r.headingErr)),
      fov:      stats(rs.map(r => r.fovErr)),
      dtMeanMs: rs.reduce((s, r) => s + r.dt, 0) / rs.length,
    }
  }
  return per
}

// ─── Scenario catalogue ───────────────────────────────────────────────────────
function defaultScenarios() {
  const base = {
    cam:        { px: 0, pz: 90, heading: 0, fov: 60 },
    photoWidth: 800,
    extent:     { near: 25, far: 100 },
    n:          6,
    noisePx:    0,
  }
  const mk = (name, patch) => ({ name, ...base, ...patch, cam: { ...base.cam, ...(patch.cam ?? {}) } })

  return [
    mk('noiseless-n4',              { n: 4 }),
    mk('noiseless-n6',              { n: 6 }),
    mk('noiseless-n12',             { n: 12 }),
    mk('noise-0.5px-n6',            { n: 6,  noisePx: 0.5 }),
    mk('noise-1px-n6',              { n: 6,  noisePx: 1 }),
    mk('noise-3px-n6',              { n: 6,  noisePx: 3 }),
    mk('noise-5px-n6',              { n: 6,  noisePx: 5 }),
    mk('noise-1px-n12',             { n: 12, noisePx: 1 }),
    mk('narrow-fov30',              { cam: { fov: 30 }, extent: { near: 40, far: 100 } }),
    mk('wide-fov90',                { cam: { fov: 90 }, extent: { near: 10, far: 60 } }),
    mk('heading-45deg',             { cam: { heading: Math.PI / 4, pz: 0 } }),
    mk('heading-145deg',            { cam: { heading: 145 * Math.PI / 180, pz: -40 } }),
    mk('camera-off-origin',         { cam: { px: 60, pz: 20, heading: -Math.PI / 3 } }),
  ]
}

// ─── Public entrypoint ────────────────────────────────────────────────────────
export function runVerification({ trials = 30, scenarios } = {}) {
  const list = scenarios ?? defaultScenarios()
  const out = []
  for (let si = 0; si < list.length; si++) {
    const s = list[si]
    const rng = lcg(1000 + si * 7919)
    const tr = []
    for (let k = 0; k < trials; k++) {
      const r = runTrial(s, rng)
      if (r) tr.push(r)
    }
    out.push({
      scenario: s.name,
      validTrials: tr.length,
      per: summarize(tr),
      spec: { n: s.n, noisePx: s.noisePx, cam: s.cam, photoWidth: s.photoWidth },
    })
  }
  return out
}

// ─── Pretty-printer (for console inspection) ──────────────────────────────────
export function formatReport(report) {
  const lines = []
  const pad = (s, w) => String(s).padEnd(w)
  const num = (v, w = 8) => (Number.isFinite(v) ? v.toFixed(2) : '—').padStart(w)

  lines.push(pad('scenario', 24) + pad('algo', 10) + 'pos med    pos p95    hdg med   fov med   ms')
  lines.push('─'.repeat(88))
  for (const r of report) {
    for (const { id } of ALGOS) {
      const p = r.per[id]
      if (!p || !p.trials) { lines.push(pad(r.scenario, 24) + pad(id, 10) + '(no valid trials)'); continue }
      lines.push(
        pad(r.scenario, 24) +
        pad(id, 10) +
        num(p.pos.median) + '   ' +
        num(p.pos.p95)    + '   ' +
        num(p.heading.median) + '   ' +
        num(p.fov.median)     + '   ' +
        num(p.dtMeanMs, 6)
      )
    }
    lines.push('')
  }
  return lines.join('\n')
}
